/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.009, 0.475, 0.06]} rotation={[3.087, -1.57, -1.627]} scale={0.791}>
        <mesh geometry={nodes.geometry_0.geometry} material={materials.geometry_0_material} position={[0.001, 0, 0]} rotation={[0, 0, -0.002]} scale={0.5} />
      </group>
      <group position={[-0.008, 0.496, -0.349]} rotation={[3.087, -1.57, -1.647]} scale={0.167}>
        <mesh geometry={nodes.geometry_0001.geometry} material={materials['geometry_0_material.001']} position={[-0.033, 0.146, 0.014]} rotation={[0, 0, -0.002]} scale={0.544} />
      </group>
      <group position={[0.133, 0.751, 0.021]} rotation={[0.003, -0.03, 0.024]} scale={0.4}>
        <mesh geometry={nodes.geometry_0004.geometry} material={materials['geometry_0_material.004']} position={[-0.849, -0.366, -1.064]} scale={0.461} />
      </group>
      <group position={[-0.098, 0.221, -0.43]} rotation={[0, 0.748, 0]} scale={0.432}>
        <mesh geometry={nodes.geometry_0002.geometry} material={materials['geometry_0_material.002']} position={[-0.003, 0, 0.003]} scale={0.5} />
      </group>
      <group position={[-0.041, 0.568, -0.337]} rotation={[-Math.PI, 0, 0]} scale={[-0.082, 0.082, 0.082]}>
        <mesh geometry={nodes.geometry_0006.geometry} material={materials['geometry_0_material.006']} position={[0.009, -0.218, 0.198]} rotation={[-0.184, 0.512, 0.69]} scale={0.502} />
      </group>
      <group position={[-0.262, 0.174, -0.432]} scale={0.348}>
        <mesh geometry={nodes.geometry_0005.geometry} material={materials['geometry_0_material.007']} position={[0.098, -0.047, 0]} scale={0.455} />
      </group>
      <group position={[-0.04, 0.575, -0.46]} rotation={[3.005, -0.764, 2.946]} scale={[0.211, 0.124, 0.138]}>
        <mesh geometry={nodes.geometry_0007.geometry} material={materials['geometry_0_material.003']} position={[0.015, 0.027, 0.064]} rotation={[-0.03, 0.026, 0.028]} scale={[0.402, 0.54, 0.403]} />
      </group>
      <group position={[-0.052, 0.579, -0.333]} rotation={[2.627, 0.806, -2.131]} scale={0.083}>
        <mesh geometry={nodes.geometry_0008.geometry} material={materials['geometry_0_material.005']} position={[0.049, -0.074, -0.02]} rotation={[-0.069, -0.101, -0.276]} scale={0.5} />
      </group>
      <mesh geometry={nodes['tripo_node_19dd656c-79e0-47a4-90a7-01b25bed6aef'].geometry} material={materials['tripo_material_19dd656c-79e0-47a4-90a7-01b25bed6aef']} position={[-0.001, 0.236, 0.004]} scale={0.479} />
      <group position={[-0.106, 0.781, -0.412]} rotation={[0, -0.129, -0.513]} scale={0.21}>
        <mesh geometry={nodes.Mesh_0005.geometry} material={materials['geometry_0_material.008']} position={[0.095, 0.001, -0.004]} scale={0.451} />
        <mesh geometry={nodes.Mesh_0005_1.geometry} material={materials.Material} position={[0.367, 0.03, 0.004]} scale={0.182} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
